[package]
name = "pcli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.1.8"
crossterm = "0.26.1"
http = "0.2.9"
logos = "0.12.1"
nom = "7.1.3"
nom_locate = "4.1.0"
rayon = "1.7.0"
thiserror = "1.0.38"
